### PR TITLE
smoothing existing meshes

### PR DESCRIPTION
**Pull request by mrbuche**
@hovey I think it is working, the sections of the original mesh are just not merged. I can redo these screenshots if you are willing to fix the journal file. It seems to want to close the gaps anyway, which is cool!

image

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">--</font> <font color="#00AFFF">smooth</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">sphere_res_1cm_noised.inp</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">s10.exo</u></font> <font color="#00AFFF">-n</font> <font color="#00AFFF">10</font>
<font color="#EC00FF"><b>    automesh 0.1.10</b></font>
     <font color="#58C7E2"><b>Reading</b></font> sphere_res_1cm_noised.inp
        <font color="#54E484"><b>Done</b></font> 5.407225ms
   <font color="#58C7E2"><b>Smoothing</b></font> s10.exo
        <font color="#54E484"><b>Done</b></font> 13.964629ms
     <font color="#58C7E2"><b>Writing</b></font> s10.exo
        <font color="#54E484"><b>Done</b></font> 8.828018ms
</pre>

image

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">--</font> <font color="#00AFFF">smooth</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">sphere_res_1cm_noised.inp</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">s50.exo</u></font> <font color="#00AFFF">-n</font> <font color="#00AFFF">50</font>
<font color="#EC00FF"><b>    automesh 0.1.10</b></font>
     <font color="#58C7E2"><b>Reading</b></font> sphere_res_1cm_noised.inp
        <font color="#54E484"><b>Done</b></font> 5.424862ms
   <font color="#58C7E2"><b>Smoothing</b></font> s50.exo
        <font color="#54E484"><b>Done</b></font> 51.128078ms
     <font color="#58C7E2"><b>Writing</b></font> s50.exo
        <font color="#54E484"><b>Done</b></font> 9.718138ms</pre>

image

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">--</font> <font color="#00AFFF">smooth</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">sphere_res_1cm_noised.inp</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">s200.exo</u></font> <font color="#00AFFF">-n</font> <font color="#00AFFF">200</font>
<font color="#EC00FF"><b>    automesh 0.1.10</b></font>
     <font color="#58C7E2"><b>Reading</b></font> sphere_res_1cm_noised.inp
        <font color="#54E484"><b>Done</b></font> 5.48193ms
   <font color="#58C7E2"><b>Smoothing</b></font> s200.exo
        <font color="#54E484"><b>Done</b></font> 188.999025ms
     <font color="#58C7E2"><b>Writing</b></font> s200.exo
        <font color="#54E484"><b>Done</b></font> 10.273104ms</pre>

image

### CODE REVIEW

**Comment by hovey** [comment]
@mrbuche That is an awesome looking result.  It definitely appears to be working.  Congratulations!  I will work on redoing the `.jou` file and getting a new `.inp`.

**Comment by hovey** [comment]
Updated the `.jou` file, added a few more imprint and merge steps, incrementally.  I will email you the updated `.inp` file.

**Comment by hovey** [comment]
@mrbuche the gap closure you mention, 

> It seems to want to close the gaps anyway, which is cool!

I believe comes from the fact that the absolutely value of the expansion parameter exceeds the smoothing parameter.

**Comment by mrbuche** [comment]
@hovey thanks for the file fix, here are the new results:

image

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">--</font> <font color="#00AFFF">smooth</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">sphere_res_1cm_noised.inp</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">s10.exo</u></font> <font color="#00AFFF">-n</font> <font color="#00AFFF">10</font>
<font color="#EC00FF"><b>    automesh 0.1.10</b></font>
     <font color="#58C7E2"><b>Reading</b></font> sphere_res_1cm_noised.inp
        <font color="#54E484"><b>Done</b></font> 6.182001ms
   <font color="#58C7E2"><b>Smoothing</b></font> s10.exo
        <font color="#54E484"><b>Done</b></font> 12.607623ms
     <font color="#58C7E2"><b>Writing</b></font> s10.exo
        <font color="#54E484"><b>Done</b></font> 9.345917ms</pre>

image

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">--</font> <font color="#00AFFF">smooth</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">sphere_res_1cm_noised.inp</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">s50.exo</u></font> <font color="#00AFFF">-n</font> <font color="#00AFFF">50</font>
<font color="#EC00FF"><b>    automesh 0.1.10</b></font>
     <font color="#58C7E2"><b>Reading</b></font> sphere_res_1cm_noised.inp
        <font color="#54E484"><b>Done</b></font> 6.201049ms
   <font color="#58C7E2"><b>Smoothing</b></font> s50.exo
        <font color="#54E484"><b>Done</b></font> 41.597516ms
     <font color="#58C7E2"><b>Writing</b></font> s50.exo
        <font color="#54E484"><b>Done</b></font> 9.401912ms
</pre>

image

<pre><font color="#F92AAD"><b>$ </b></font><font color="#005FD7">cargo</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-qr</font> <font color="#00AFFF">--</font> <font color="#00AFFF">smooth</font> <font color="#00AFFF">-i</font> <font color="#00AFFF"><u style="text-decoration-style:single">sphere_res_1cm_noised.inp</u></font> <font color="#00AFFF">-o</font> <font color="#00AFFF"><u style="text-decoration-style:single">s200.exo</u></font> <font color="#00AFFF">-n</font> <font color="#00AFFF">200</font>
<font color="#EC00FF"><b>    automesh 0.1.10</b></font>
     <font color="#58C7E2"><b>Reading</b></font> sphere_res_1cm_noised.inp
        <font color="#54E484"><b>Done</b></font> 6.121438ms
   <font color="#58C7E2"><b>Smoothing</b></font> s200.exo
        <font color="#54E484"><b>Done</b></font> 160.538074ms
     <font color="#58C7E2"><b>Writing</b></font> s200.exo
        <font color="#54E484"><b>Done</b></font> 9.910398ms</pre>

image

**Comment by hovey** [comment]
@mrbuche that looks awesome!  🥇

**Pull request merged**
